"""create_readme_tables

Revision ID: 639127892aed
Revises: 81e45f9481e4
Create Date: 2025-02-15 16:54:58.080565

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "639127892aed"
down_revision: Union[str, None] = "81e45f9481e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_templates_id", table_name="templates")
    op.drop_table("templates")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "templates",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("preview_image", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("featured", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="templates_pkey"),
    )
    op.create_index("ix_templates_id", "templates", ["id"], unique=False)
    # ### end Alembic commands ###
