"""Add readme models and chat models

Revision ID: 81e45f9481e4
Revises: b7a404ea711a
Create Date: 2025-02-14 22:09:37.703338

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "81e45f9481e4"
down_revision: Union[str, None] = "b7a404ea711a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
