"""Add title to template model

Revision ID: b49aa35a941b
Revises: e8412bb28d15
Create Date: 2025-02-16 20:29:29.140830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b49aa35a941b"
down_revision: Union[str, None] = "e8412bb28d15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("title", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "title")
    # ### end Alembic commands ###
