"""Make user id mandatory

Revision ID: baa9640e39e4
Revises: 82af992d75c8
Create Date: 2025-02-08 17:47:15.258472

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "baa9640e39e4"
down_revision: Union[str, None] = "82af992d75c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
