/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as HomeImport } from "./routes/_home"
import { Route as IndexImport } from "./routes/index"
import { Route as HomeHomeImport } from "./routes/_home/home"
import { Route as HomeTemplatesIndexImport } from "./routes/_home/templates/index"
import { Route as HomeTemplatesCreateIndexImport } from "./routes/_home/templates/create/index"

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: "/_home",
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const HomeHomeRoute = HomeHomeImport.update({
  id: "/home",
  path: "/home",
  getParentRoute: () => HomeRoute,
} as any)

const HomeTemplatesIndexRoute = HomeTemplatesIndexImport.update({
  id: "/templates/",
  path: "/templates/",
  getParentRoute: () => HomeRoute,
} as any)

const HomeTemplatesCreateIndexRoute = HomeTemplatesCreateIndexImport.update({
  id: "/templates/create/",
  path: "/templates/create/",
  getParentRoute: () => HomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    "/_home": {
      id: "/_home"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    "/_home/home": {
      id: "/_home/home"
      path: "/home"
      fullPath: "/home"
      preLoaderRoute: typeof HomeHomeImport
      parentRoute: typeof HomeImport
    }
    "/_home/templates/": {
      id: "/_home/templates/"
      path: "/templates"
      fullPath: "/templates"
      preLoaderRoute: typeof HomeTemplatesIndexImport
      parentRoute: typeof HomeImport
    }
    "/_home/templates/create/": {
      id: "/_home/templates/create/"
      path: "/templates/create"
      fullPath: "/templates/create"
      preLoaderRoute: typeof HomeTemplatesCreateIndexImport
      parentRoute: typeof HomeImport
    }
  }
}

// Create and export the route tree

interface HomeRouteChildren {
  HomeHomeRoute: typeof HomeHomeRoute
  HomeTemplatesIndexRoute: typeof HomeTemplatesIndexRoute
  HomeTemplatesCreateIndexRoute: typeof HomeTemplatesCreateIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeHomeRoute: HomeHomeRoute,
  HomeTemplatesIndexRoute: HomeTemplatesIndexRoute,
  HomeTemplatesCreateIndexRoute: HomeTemplatesCreateIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "": typeof HomeRouteWithChildren
  "/home": typeof HomeHomeRoute
  "/templates": typeof HomeTemplatesIndexRoute
  "/templates/create": typeof HomeTemplatesCreateIndexRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "": typeof HomeRouteWithChildren
  "/home": typeof HomeHomeRoute
  "/templates": typeof HomeTemplatesIndexRoute
  "/templates/create": typeof HomeTemplatesCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexRoute
  "/_home": typeof HomeRouteWithChildren
  "/_home/home": typeof HomeHomeRoute
  "/_home/templates/": typeof HomeTemplatesIndexRoute
  "/_home/templates/create/": typeof HomeTemplatesCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "" | "/home" | "/templates" | "/templates/create"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "" | "/home" | "/templates" | "/templates/create"
  id:
    | "__root__"
    | "/"
    | "/_home"
    | "/_home/home"
    | "/_home/templates/"
    | "/_home/templates/create/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_home"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_home": {
      "filePath": "_home.tsx",
      "children": [
        "/_home/home",
        "/_home/templates/",
        "/_home/templates/create/"
      ]
    },
    "/_home/home": {
      "filePath": "_home/home.tsx",
      "parent": "/_home"
    },
    "/_home/templates/": {
      "filePath": "_home/templates/index.tsx",
      "parent": "/_home"
    },
    "/_home/templates/create/": {
      "filePath": "_home/templates/create/index.tsx",
      "parent": "/_home"
    }
  }
}
ROUTE_MANIFEST_END */
