name: Backend Checks

on:
  push:
    branches: [ main ]
    paths:
      - 'readme_ai_backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'readme_ai_backend/**'
  workflow_dispatch:

jobs:
  test-lint-typecheck:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./readme_ai_backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
          path: ./readme_ai_backend/.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('./readme_ai_backend/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: poetry run pytest || true

      - name: Run type checking
        run: poetry run mypy .

      - name: Run linting
        run: |
          poetry run ruff check .
          poetry run black . --check

      - name: Security checks
        run: poetry run safety check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
